version: '3'
services:
  web:
    build: .  
    ports:
     - 3035:80
    environment:
      - "VIRTUAL_HOST=poll.gplite.net"
    container_name: poll_app
    restart: always

#networks:
#    default:
#        external:
#            name: wpnetwork 